<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="stylesheet.css"/>
        <link href='http://fonts.googleapis.com/css?family=Gafata' rel='stylesheet' type='text/css'/>
        <title>Terms and Conditions</title>
    </head>
    <body>
        <ul class="navbar">
            <li><a href="mainpage.php">Home</a></li>
            <li><a href="browse.php">Browse</a></li>
            <li><a href="list_item.php">List Item</a></li>
            <li><a href="logout_confirm.php">Logout</a></li>
        </ul>
        <div class="content">
        <h1>Terms and Conditions</h1>
<!--        sample courtesy of the sample network http://thesamplenetwork.com/terms-and-conditions/-->
        <p>

These terms and conditions (“Standard Terms”) are incorporated by reference into the request (the “Request”) submitted by the below indicated Client or its agency (jointly and severally, “Client”) to The Sample Network. In the event of a conflict between these Standard Terms and theRequest , these Standard Terms shall govern. These Standard Terms and the Request are collectively referred to herein as the “Agreement.” </p>

<h1>1. Acceptance/Rejection of Requests</h1>

<p>Submission of your Request is merely an offer to The Sample Network to use commercially reasonable efforts to provide the services and deliver the deliverables described in the Request for the price proposed therein. The Request is not binding on The Sample Network unless or until The Sample Network delivers written confirmation of its acceptance of the Request to the Client. The Sample Network reserves the right, in its sole discretion, to accept or reject any Request. Acceptance of a Request only obligates The Sample Network to use commercially reasonable efforts to provide the services described in the Request. In the event The Sample Network accepts a Request , Client shall have thirty (60) days to make its survey available to The Sample Network as required by the Request . In the event Client fails to do so within such sixty (60) day period, the Agreement shall immediately terminate. In the event The Sample Network rejects a Request , it may propose an alternative price and/or scope of work for the Request, which such alternative proposal shall be merely an offer to the Client to provide such services and deliver such deliverables as specified in the alternative proposal. Unless otherwise stated in such an alternative proposal, the alternative proposal shall be valid for a period of sixty (60) days from the date of sending. If not accepted by Client (as confirmed in a writing received by The Sample Network) during such period, The Sample Network’s alternative proposal shall be automatically revoked.</p>

<h1>2. Term of Payment</h1>

<p>Promptly after sending written confirmation of its acceptance of Client’s Request , The Sample Network will invoice Clientthe amount set forth in the Request. Unless otherwise stated in The Samples Network’s insertion order: (i) payment of fifty percent (50%) of such amount shall be payable to The Sample Network upon receipt of the invoice; and (ii) payment of the remaining fifty percent (50%) of such amount shall be payable upon The Sample Network’s delivery to Client of the deliverables set forth in the Request. In the event The Sample Network is unable to obtain the number of surveys specified in an Request in accordance with the terms of such Request, The Sample Network shall: (i) reduce the Request price charged to Client by a percentage equal to the percentage deficiency in surveys it is able to deliver in accordance with the Request; and (ii) provide Client with a ten percent (10%) discount on its next Request accepted by The Sample Network. Amounts unpaid by Client after thirty (30) days shall bear interest at the rate of one-and-one-half percent (1.5%) per month (or the highest rate permitted by law, if less) until paid in full. In the event of any failure by Client to make payment, Client will be responsible for all reasonable expenses (including attorneys’ fees) incurred by The Sample Network in collecting such amounts. Without limiting any other remedy available to The Sample Network in law or equity, in the event that Client is in default of its obligations hereunder, including without limitation delinquent in payments required to be made hereunder, Client shall upon notice by The Sample Network cease-and-desist from any further use of any information, materials or other deliverables acquired under this Agreement. All payments due hereunder are in U.S. dollars and are exclusive of any applicable taxes. Client shall be responsible for all applicable taxes.</p>

<h1>3. Confidentiality</h1>

<p>During the term of this Agreement, and until such time as the “Confidential Information” (as defined below) is no longer protected as a trade secret or confidential information under New Jersey law, neither party will use or disclose any “Confidential Information” of the other party except as specifically contemplated herein. “Confidential Information” means information that: (1) is sufficiently secret to derive economic value, actual or potential, from not being generally known to other persons who can obtain economic value from its disclosure or use; and (2) is the subject of efforts that are reasonable under the circumstances to maintain its secrecy or confidentiality. Subject to the foregoing: (i) Confidential Information of The Sample Network includes, but is not limited to, the sources from which it obtains survey respondents, and the methods by which it obtains survey respondents; and Confidential Information of either party includes, but is not limited to, technical or non-technical data, a formula, pattern, compilation, program, device, method, technique, drawing, process, financial data, or list of actual or potential customers or suppliers, the advertisement before publication, and the terms of the Request. Confidential Information does not include information that: (i) has been independently developed by the receiving party without access to the other party’s Confidential Information; (ii) has become publicly known through no breach of this Section by the receiving party; (iii) has been rightfully received from a third party authorized to make such disclosure; (iv) has been approved for release in writing by the disclosing party; or (v) is required to be disclosed by a competent legal or governmental authority. At the request of the disclosing party, the receiving party shall return all of the disclosing party’s Confidential Information to the disclosing party.</p>

<h1>4. Warranty; Disclaimer</h1>

<p>The Sample Network warrants that: (i) it will provide its services hereunder in a professional and workmanlike manner; and (ii) the third parties with which it contracts to assist it in obtaining respondents for surveys are required by their agreements with The Sample Network to comply with the federal CAN-SPAM Act. WITH THE EXCEPTION OF THE PRECEDING WARRANTY, THE SAMPLE NETWORK MAKES NO WARRANTY WITH RESPECT TO ANY MATTER INCLUDING, WITHOUT LIMITATION, ITS SERVICES AND DELIVERABLES HEREUNDER, AND EXPRESSLY DISCLAIMS ALL OTHER WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, THE IMPLIED WARRANTIES OF NONINFRINGEMENT, TITLE, MERCHANTABILITY, FITNESS FOR ANY PARTICULAR PURPOSE, AND ANY REPRESENTATION OR WARRANTY REGARDING THE PERFORMANCE, AVAILABILITY OR FUNCTIONALITY OF ANY ASPECT OF THE SERVICES OR DELIVERABLES HEREUNDER.</p>

<h1>5. Limitations of Liability</h1>

<p>In the event that The Sample Network fails to deliver any services or deliverables, including completed surveys, in accordance with, and within the time period(s) set forth in, the applicable Request, or in the event of any other failure, technical or otherwise of such services or deliverables, the entire liability of The Sample Network and the exclusive remedy of Client shall be limited to the price reduction and future credit set forth in Paragraph 3 above. IN NO EVENT SHALL THE SAMPLE NETWORK BE LIABLE UNDER THIS AGREEMENT FOR ANY CONSEQUENTIAL, SPECIAL, INDIRECT OR PUNITIVE DAMAGES INCLUDING, WITHOUT LIMITATION, LOST PROFITS, WHETHER BASED IN CONTRACT, TORT OR OTHERWISE, EVEN IF THE SAMPLE NETWORK HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. IN NO EVENT SHALL THE SAMPLE NETWORK’S AGGREGATE LIABILITY UNDER THIS AGREEMENT FOR ANY CLAIM EXCEED THE AGGREGATE AMOUNT OF THE ORDER. Without limiting the foregoing, The Sample Network shall have no liability for any failure or delay resulting from any governmental action, fire, flood, insurrection, earthquake, power failure, riot, explosion, embargo, strikes whether legal or illegal, labor or material shortage, transportation interruption of any kind, work slowdown or any other condition affecting production or delivery in any manner beyond the control of The Sample Network. Client acknowledges that The Sample Network has entered into this Agreement in reliance upon the limitations of liability set forth herein and that the same is an essential basis of the bargain between the parties.</p>

<h1>6. Miscellaneous</h1>

<p>This Agreement and the Request constitute the entire agreement of the parties with respect to the subject matter of the Request. This Agreement shall be governed by and construed in accordance with the laws of the State of New Jersey, without giving effect to principles of conflicts of law. Any dispute arising out of or relating to this Agreement shall be brought exclusively in the federal or state courts located in the State of New Jersey, the jurisdiction and venue of which the parties irrevocably consent to for this purpose. This Agreement may be amended only by a writing executed by a duly authorized representative of each party. Client shall make no public announcement regarding the existence or content of the Request without The Sample Network’s prior written approval, which approval shall not be unreasonably withheld. Any notices under this Agreement shall be sent to the addresses set forth in the Request (or in a separate writing) by facsimile or nationally-recognized express delivery service and deemed given upon receipt. The waiver of any breach or default of this Agreement will not constitute a waiver of any subsequent breach or default, and will not act to amend or negate the rights of the waiving party. If any provision contained in this Agreement is determined to be invalid, illegal or unenforceable in any respect under any applicable law, then such provision will be severed and replaced with a new provision that most closely reflects the original intention of the parties, and the remaining provisions of this Agreement will remain in full force and effect.

By submitting its Request to The Sample Network, Client assent and agrees to these Standard Terms.

- See more <a href="http://thesamplenetwork.com/terms-and-conditions/#sthash.UlfdX0Lo.dpuf">Here</a></p>
        </div>
    </body>
</html>